### ISSUE TITLE
async 2.0 changes callpack param order

### ISSUE THREAD

**Issue by krazik** [feross/run-auto#7]
not sure if you want to update to match?

https://github.com/caolan/async/blob/master/CHANGELOG.md#breaking-changes

results and callback argument order have been swapped for 2.0.x

**Comment by feross** [comment]
Sure, I like this change. It follows the Node.js callback-last convention.

**Comment by feross** [comment]
Released as v2.0.0.

**Comment by krazik** [comment]
awesome, thanks! 👍

**Comment by feross** [comment]
👍
